# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a47d3ba3f2258956c66ac9da8149cafc29de4a49eb76c4bc614a11414b415dca58b6999b6deb570c97014e513064f2741622319ca65e0b4428209292f35c571

test:
  secret_key_base: 1c49e46e10fc1dfd33e2e1bebb3974afb89ead748c4a7babe79fb385231dc86af207bb459788b058b964be52302514e0e2700a3f204bc1ec44647ddae5cfc0a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
